#!/usr/bin/env python3
"""Delete devkit games and manage Steam client.

This script provides functionality to:
- Delete individual devkit titles
- Delete all devkit titles
- Reset the Steam client (SteamOS only)

Modified for Bazzite/Universal devkit - uses steam-shortcut-manager for shortcut sync.
"""

import sys
import os
import logging
import argparse
import subprocess
import shutil

import devkit_utils.resolve

logging.basicConfig(format='%(message)s', level=logging.DEBUG)
logger = logging.getLogger(__name__)

DEVKIT_TOOL_FOLDER = os.path.expanduser('~/devkit-game')
RESTART_SESSION = '/usr/bin/steamos-session-select gamescope'


def delete_title(title_name):
    """Delete a single devkit title.

    Args:
        title_name: Name of the title to delete
    """
    gamepath = os.path.expanduser(os.path.join('~/devkit-game', title_name))
    if not os.path.isdir(gamepath):
        logger.error(f'Not found: {gamepath}')
        return False

    # Delete the directory
    logger.info(f'Deleting {gamepath}')
    shutil.rmtree(gamepath)

    # Also delete associated config files
    for suffix in ['-argv.json', '-settings.json']:
        config_file = os.path.expanduser(os.path.join('~/devkit-game', title_name + suffix))
        if os.path.exists(config_file):
            logger.info(f'Deleting config file {config_file}')
            os.unlink(config_file)

    return True


def delete_all_titles():
    """Delete all devkit titles."""
    devkit_path = os.path.expanduser('~/devkit-game')
    if not os.path.exists(devkit_path):
        logger.info('No devkit-game directory found')
        return

    # Delete everything in ~/devkit-game
    for entry in os.scandir(devkit_path):
        entry_path = entry.path
        logger.info(f'Deleting {entry_path}')
        if entry.is_dir():
            shutil.rmtree(entry_path)
        else:
            os.unlink(entry_path)


def is_steamos():
    """Check if running on SteamOS."""
    try:
        with open('/etc/os-release', 'r') as f:
            content = f.read()
            return 'SteamOS' in content or 'VARIANT_ID' in content and 'steamdeck' in content.lower()
    except FileNotFoundError:
        return False


if __name__ == '__main__':
    parser = argparse.ArgumentParser(
        description='Delete devkit games and manage Steam client'
    )
    parser.add_argument('--verbose', required=False, action='store_true')
    parser.add_argument('--delete-title', required=False, action='store',
                        help='Delete a devkit title by name')
    parser.add_argument('--delete-all-titles', required=False, action='store_true',
                        default=False, help='Delete all devkit titles uploaded')
    parser.add_argument('--reset-steam-client', required=False, action='store_true',
                        default=False,
                        help='Reset Steam client and delete all local Steam content (SteamOS only)')
    conf = parser.parse_args()

    if conf.verbose:
        logger.setLevel(logging.DEBUG)
    else:
        logger.setLevel(logging.INFO)

    if conf.delete_all_titles:
        delete_all_titles()
    elif conf.delete_title:
        delete_title(conf.delete_title)

    # Synchronize the Steam client's view of the devkit games with the on-disk state
    try:
        devkit_utils.resolve.resolve_shortcuts()
    except Exception as e:
        logger.warning(f'Steam client sync of devkit games failed: {e}')

    if conf.reset_steam_client:
        if not is_steamos():
            logger.warning(
                'Steam client reset is only supported on SteamOS. '
                'On other systems, please reset Steam manually.'
            )
        else:
            # First make sure any sideloaded trampoline has been deleted
            devkit_steam_trampoline_path = os.path.join(DEVKIT_TOOL_FOLDER, 'devkit-steam')
            if os.path.exists(devkit_steam_trampoline_path):
                os.unlink(devkit_steam_trampoline_path)

            # Wipe the local Steam install
            steam_path = os.path.expanduser('~/.local/share/Steam')
            if os.path.exists(steam_path):
                logger.info(f'Removing Steam directory: {steam_path}')
                shutil.rmtree(steam_path)

            # Restart the session, which will initiate a reinstall of Steam from the OS client
            logger.info('Restarting Steam session...')
            subprocess.check_call(RESTART_SESSION, shell=True)
