#!/usr/bin/env python3

import sys
import os
import logging
import argparse
import getpass
import json
import shutil
import subprocess

logging.basicConfig(format='%(message)s', level=logging.DEBUG)
logger = logging.getLogger(__name__)

DEVKIT_TOOL_FOLDER = os.path.expanduser('~/devkit-game')

if __name__ == '__main__':
    parser = argparse.ArgumentParser()
    parser.add_argument('--verbose', required=False, action='store_true')
    parser.add_argument('--gameid', required=True, action='store')
    parser.add_argument('--restart-steam', required=False, default='1', action='store')
    conf = parser.parse_args()

    if conf.verbose:
        logger.setLevel(logging.DEBUG)
    else:
        logger.setLevel(logging.INFO)

    directory = os.path.join(
        os.path.expanduser(DEVKIT_TOOL_FOLDER),
        conf.gameid
    )
    os.makedirs(directory, exist_ok=True)

    if conf.gameid == 'steamdeckard' and int(conf.restart_steam) == 1:
        # tear down steamvr before we start uploading, we mask first to prevent auto restart
        subprocess.check_call('systemctl --user mask steam ; systemctl --user stop steam', shell=True, stdout=sys.stderr, stderr=subprocess.STDOUT)

    ret = {
        'user': getpass.getuser(),
        'directory': directory,
    }
    print(json.dumps(ret))
